name: forecast_env
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - lightgbm
  - statsmodels
  - prophet
  - pip
  - pip:
    - neuralforecast
    - tqdm
